name: qtscan
base: core24
version: '0.1.14'
summary: QtScan QR scanner
description: |
  QtScan scans QR codes from a camera or image files and can generate QR codes from text.
icon: snap/icon-0.png
source-code: https://github.com/vinsom68/QtScan


grade: stable
confinement: strict

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv/archive/4.12.0.tar.gz
    source-type: tar
    override-pull: |
      snapcraftctl pull
      curl -L -o "$SNAPCRAFT_PART_SRC/opencv_contrib-4.12.0.tar.gz" \
        https://github.com/opencv/opencv_contrib/archive/4.12.0.tar.gz
      tar -xzf "$SNAPCRAFT_PART_SRC/opencv_contrib-4.12.0.tar.gz" -C "$SNAPCRAFT_PART_SRC"
      mv "$SNAPCRAFT_PART_SRC/opencv_contrib-4.12.0" "$SNAPCRAFT_PART_SRC/opencv_contrib"
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTS=OFF
      - -DBUILD_PERF_TESTS=OFF
      - -DBUILD_DOCS=OFF
      - -DBUILD_EXAMPLES=OFF
      - -DOPENCV_EXTRA_MODULES_PATH=$SNAPCRAFT_PART_SRC/opencv_contrib/modules
    build-packages:
      - build-essential
      - curl
      - ca-certificates
      - cmake
      - pkg-config
      - libgtk-3-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libjpeg-dev
      - libpng-dev
    stage-packages:
      - libgtk-3-0
      - libavcodec60
      - libavformat60
      - libswscale7
      - libv4l-0
      - libjpeg-turbo8
      - libpng16-16
      - libwebpdemux2
      - libopenexr-3-1-30
    override-prime: |
      snapcraftctl prime
      arch_triplet="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
      libdir="$SNAPCRAFT_PRIME/usr/lib/$arch_triplet"
      if [ -d "$libdir" ]; then
        for base in libglib-2.0.so.0 libgobject-2.0.so.0 libgio-2.0.so.0 libgthread-2.0.so.0 libgmodule-2.0.so.0; do
          found="$(ls -1 "$libdir"/${base}.* 2>/dev/null | sort -V)"
          latest="$(printf "%s\n" "$found" | tail -n 1)"
          if [ -n "$latest" ]; then
            ln -sf "$(basename "$latest")" "$libdir/$base"
          fi
        done
      fi
      arch_triplet="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
      libdir="$SNAPCRAFT_PRIME/usr/lib/$arch_triplet"
      if [ -d "$libdir" ]; then
        for lib in "$libdir"/libopencv_*.so.*; do
          [ -e "$lib" ] || continue
          base="$(basename "$lib")"
          case "$base" in
            *.so.*.*)
              soname="${base%.*}"
              ln -sf "$base" "$libdir/$soname"
              ;;
          esac
        done
      fi
  qtscan:
    plugin: dotnet
    source: .
    after:
      - opencv
    dotnet-configuration: Release
    dotnet-project: QtScan/QtScan.csproj
    dotnet-self-contained: true
    override-build: |
      set -euo pipefail
      export NUGET_PACKAGES="$SNAPCRAFT_PART_BUILD/.nuget/packages"
      dotnet restore QtScan/QtScan.csproj \
        --runtime ubuntu.24.04-x64 \
        --packages "$NUGET_PACKAGES"
      dotnet publish QtScan/QtScan.csproj \
        --configuration Release \
        --runtime ubuntu.24.04-x64 \
        --self-contained true \
        --framework net9.0 \
        --output "$SNAPCRAFT_PART_INSTALL" \
        --no-restore
      # Ensure OpenCvSharp native loader can find its shared objects.
      arch_triplet="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
      target_lib="$SNAPCRAFT_PART_INSTALL/usr/lib/$arch_triplet"
      mkdir -p "$target_lib"
      runtime_root="$NUGET_PACKAGES/opencvsharp4.unofficial.runtime.ubuntu.24.04-x64"
      runtime_version="$(ls -1d "$runtime_root"/* 2>/dev/null | sort -V | tail -n 1)"
      runtime_dir=""
      if [ -n "$runtime_version" ]; then
        if [ -d "$runtime_version/runtimes/ubuntu.24.04-x64/native" ]; then
          runtime_dir="$runtime_version/runtimes/ubuntu.24.04-x64/native"
        elif [ -d "$runtime_version/runtimes/linux-x64/native" ]; then
          runtime_dir="$runtime_version/runtimes/linux-x64/native"
        fi
      fi
      if [ -z "${runtime_dir:-}" ]; then
        echo "OpenCvSharp runtime native libs not found." >&2
        exit 1
      fi
      cp -av "$runtime_dir"/libOpenCvSharpExtern.so* "$SNAPCRAFT_PART_INSTALL/"
      cp -av "$runtime_dir"/libOpenCvSharpExtern.so* "$target_lib/"
      if [ -f "$SNAPCRAFT_PART_INSTALL/libOpenCvSharpExtern.so" ]; then
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/OpenCvSharpExtern.so"
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/OpenCvSharpExtern"
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/libOpenCvSharpExtern"
      fi
    # Adjust if you use a different output name or add resources.
    stage-packages:
      - liblttng-ust1t64
      - libglib2.0-0t64
      - libsm6
      - libx11-6
      - libxext6
      - libxrender1
      - libxrandr2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxcomposite1
      - libxdamage1
      - libfontconfig1
      - libfreetype6
      - libstdc++6
      - libgl1
      - libgl1-mesa-dri
      - libtesseract5
      - liblept5
      - libgtk2.0-0
      # OpenCV runtime libs (Ubuntu 24.04)
    override-stage: |
      snapcraftctl stage
    override-prime: |
      snapcraftctl prime
    build-packages:
      - dotnet-sdk-9.0

apps:
  qtscan:
    command: QtScan
    extensions:
      - dotnet9
    environment:
      LD_LIBRARY_PATH: "$SNAP:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
    plugs:
      - camera
      - home
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - network
      - removable-media
