name: qtscan
base: core24
version: '0.1.0'
summary: QtScan QR scanner
description: |
  QtScan scans QR codes from a camera or image files and can generate QR codes from text.
icon: snap/icon-4.png
source-code: https://github.com/vinsom68/QtScan


grade: devel
confinement: strict

parts:
  opencv:
    plugin: cmake
    source: https://github.com/opencv/opencv/archive/4.12.0.tar.gz
    source-type: tar
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_SHARED_LIBS=ON
      - -DBUILD_TESTS=OFF
      - -DBUILD_PERF_TESTS=OFF
      - -DBUILD_DOCS=OFF
      - -DBUILD_EXAMPLES=OFF
      - -DBUILD_LIST=core,imgproc,imgcodecs,videoio,objdetect
    build-packages:
      - build-essential
      - curl
      - ca-certificates
      - cmake
      - pkg-config
      - libgtk-3-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libjpeg-dev
      - libpng-dev
    stage-packages:
      - libgtk-3-0
      - libavcodec60
      - libavformat60
      - libswscale7
      - libv4l-0
      - libjpeg-turbo8
      - libpng16-16
  qtscan:
    plugin: dotnet
    source: .
    after:
      - opencv
    dotnet-configuration: Release
    dotnet-project: QtScan/QtScan.csproj
    dotnet-self-contained: true
    override-build: |
      set -euo pipefail
      export NUGET_PACKAGES="$SNAPCRAFT_PART_BUILD/.nuget/packages"
      dotnet restore QtScan/QtScan.csproj \
        --runtime ubuntu.24.04-x64 \
        --packages "$NUGET_PACKAGES"
      dotnet publish QtScan/QtScan.csproj \
        --configuration Release \
        --runtime ubuntu.24.04-x64 \
        --self-contained true \
        --framework net9.0 \
        --output "$SNAPCRAFT_PART_INSTALL" \
        --no-restore
      # Ensure OpenCvSharp native loader can find its shared objects.
      arch_triplet="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"
      target_lib="$SNAPCRAFT_PART_INSTALL/usr/lib/$arch_triplet"
      mkdir -p "$target_lib"
      runtime_root="$NUGET_PACKAGES/oneware.opencvsharp4.runtime.ubuntu.24.04-x64"
      runtime_version="$(ls -1d "$runtime_root"/* 2>/dev/null | sort -V | tail -n 1)"
      runtime_dir=""
      if [ -n "$runtime_version" ]; then
        if [ -d "$runtime_version/runtimes/ubuntu.24.04-x64/native" ]; then
          runtime_dir="$runtime_version/runtimes/ubuntu.24.04-x64/native"
        elif [ -d "$runtime_version/runtimes/linux-x64/native" ]; then
          runtime_dir="$runtime_version/runtimes/linux-x64/native"
        fi
      fi
      if [ -z "$runtime_dir" ]; then
        runtime_dir="$(find "$NUGET_PACKAGES" -path "*/runtimes/*/native/libOpenCvSharpExtern.so*" -print 2>/dev/null | sort -V | tail -n 1 | xargs -r dirname)"
      fi
      if [ -z "${runtime_dir:-}" ]; then
        echo "OpenCvSharp runtime native libs not found." >&2
        exit 1
      fi
      cp -av "$runtime_dir"/libOpenCvSharpExtern.so* "$SNAPCRAFT_PART_INSTALL/"
      cp -av "$runtime_dir"/libOpenCvSharpExtern.so* "$target_lib/"
      if [ -f "$SNAPCRAFT_PART_INSTALL/libOpenCvSharpExtern.so" ]; then
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/OpenCvSharpExtern.so"
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/OpenCvSharpExtern"
        ln -sf "libOpenCvSharpExtern.so" "$SNAPCRAFT_PART_INSTALL/libOpenCvSharpExtern"
      fi
    # Adjust if you use a different output name or add resources.
    stage-packages:
      - liblttng-ust1t64
      - libglib2.0-0
      - libsm6
      - libx11-6
      - libxext6
      - libxrender1
      - libxrandr2
      - libxcursor1
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxcomposite1
      - libxdamage1
      - libfontconfig1
      - libfreetype6
      - libstdc++6
      # OpenCV runtime libs (Ubuntu 24.04)
    override-stage: |
      snapcraftctl stage
    override-prime: |
      snapcraftctl prime
    build-packages:
      - dotnet-sdk-9.0

apps:
  qtscan:
    command: QtScan
    extensions:
      - dotnet9
    environment:
      LD_LIBRARY_PATH: "$SNAP:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
    plugs:
      - camera
      - home
      - opengl
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - network
      - removable-media
